In [60]:
#########################################################
#                                                       #
#       QUANTUM GENETIC ALGORITHM (24.05.2016)          #
#                                                       #
#               R. Lahoz-Beltra                         #
#                                                       #
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND   #
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT #
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY #
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  #
# THE SOFWTARE CAN BE USED BY ANYONE SOLELY FOR THE     #
# PURPOSES OF EDUCATION AND RESEARCH.                   #
#                                                       #
#########################################################
import math
import numpy as np
import matplotlib.pyplot as plt

#########################################################
# ALGORITHM PARAMETERS                                  #
#########################################################
N=10                  # Define here the population size
Genome=4              # Define here the chromosome length
generation_max=1    # Define here the maximum number of 
                      # generations/iterations

#########################################################
# VARIABLES ALGORITHM                                   #
#########################################################
popSize=N
genomeLength=Genome
top_bottom=3
QuBitZero = np.array([[1],[0]])
QuBitOne = np.array([[0],[1]])
AlphaBeta = np.empty([top_bottom])
fitness = np.empty([popSize])
probability = np.empty([popSize])
# qpv: quantum chromosome (or population vector, QPV)
qpv = np.empty([popSize, genomeLength, top_bottom])         
nqpv = np.empty([popSize, genomeLength, top_bottom])
# chromosome: classical chromosome
chromosome = np.empty([popSize, genomeLength],dtype=int) 
child1 = np.empty([popSize, genomeLength, top_bottom])
child2 = np.empty([popSize, genomeLength, top_bottom])
best_chrom = np.empty([generation_max])

# Initialization global variables
theta=0;
iteration=0;
the_best_chrom=0;
generation=0;

#########################################################
# QUANTUM POPULATION INITIALIZATION                     #
#########################################################
def Init_population():
    # Hadamard gate
    r2=math.sqrt(2.0)
    h=np.array([[1/r2,1/r2],[1/r2,-1/r2]])
    # Rotation Q-gate
    theta=0;
    rot =np.empty([2,2])
    # Initial population array (individual x chromosome)
    i=1; j=1;
    for i in range(0,popSize):
     for j in range(0,genomeLength):
        theta=np.random.uniform(0,1)*90
        theta=math.radians(theta)
        rot[0,0]=math.cos(theta); rot[0,1]=-math.sin(theta);
        rot[1,0]=math.sin(theta); rot[1,1]=math.cos(theta);
        AlphaBeta[0]=rot[0,0]*(h[0][0]*QuBitZero[0])+rot[0,1]*(h[0][1]*QuBitZero[1])
        AlphaBeta[1]=rot[1,0]*(h[1][0]*QuBitZero[0])+rot[1,1]*(h[1][1]*QuBitZero[1])
        # alpha squared          
        qpv[i,j,0]=np.around(2*pow(AlphaBeta[0],2),2) 
        # beta squared
        qpv[i,j,1]=np.around(2*pow(AlphaBeta[1],2),2) 

#########################################################
# SHOW QUANTUM POPULATION                               #
#########################################################
def Show_population():
    i=1; j=1;
    for i in range(0,popSize):
        print()
        print()
        print("qpv = ",i," : ")
        print()
        for j in range(0,genomeLength):
          print(qpv[i, j, 0],end="")
          print(" ",end="")
        print()
        for j in range(0,genomeLength):
          print(qpv[i, j, 1],end="")
          print(" ",end="")
    print()
    
#########################################################
# MAKE A MEASURE                                        #
#########################################################
# p_alpha: probability of finding qubit in alpha state
def Measure(p_alpha):
    for i in range(0,popSize):
        print()
        for j in range(0,genomeLength):
            if p_alpha<=qpv[i, j, 0]:
                chromosome[i,j]=0
            else:
                chromosome[i,j]=1
            print(chromosome[i,j]," ",end="")
        print()
    print()

#########################################################
# FITNESS EVALUATION                                    #
#########################################################
def Fitness_evaluation(generation,learning_rate,num_qubits,num_epoch):
    i=1; j=1; fitness_total=0; sum_sqr=0;
    fitness_average=0; variance=0; 
    fitness = np.empty([popSize])
    for i in range(1,popSize):
        fitness[i]=0

#########################################################
# Define your problem in this section. For instance:    #
#                                                       #
# Let f(x)=abs(x-5/2+sin(x)) be a function that takes   #
# values in the range 0<=x<=15. Within this range f(x)  #
# has a maximum value at x=11 (binary is equal to 1011) #
#########################################################
    for i in range(0,popSize):
       for j in range(0,genomeLength):
#            # translate from binary to decimal value
#            x=x+chromosome[i,j]*pow(2,genomeLength-j-1)
#            # replaces the value of x in the function f(x)
#            y= np.fabs((x-5)/(2+np.sin(x)))
#            # the fitness value is calculated below:
#            # (Note that in this example is multiplied
#            # by a scale value, e.g. 100)
#            fitness[i]=y*100
            Qmodel = QShallowRegressionLSTM(num_sensors=4, hidden_units=num_hidden_units, n_qubits=3)
            loss_function = nn.MSELoss()
            optimizer = torch.optim.Adagrad(Qmodel.parameters(), lr=learning_rate[i-1])
            
            quantum_loss_train = []
            quantum_loss_test = []
            print("Untrained test\n--------")
            start = time.time()
            test_loss = test_model(test_loader, Qmodel, loss_function)
            end = time.time()
            print("Execution time", end - start)
            quantum_loss_test.append(test_loss)

            for ix_epoch in range(chromosome[i,j]):
                print(f"Epoch {ix_epoch}\n---------")
                start = time.time()
                train_loss = train_model(train_loader, Qmodel, loss_function, optimizer=optimizer)
                test_loss = test_model(test_loader, Qmodel, loss_function)
                end = time.time()
                print("Execution time", end - start)
                quantum_loss_train.append(train_loss)
                quantum_loss_test.append(test_loss)
            fitness_epoch=0
            for i in range(len(quantum_loss_train)):
                fitness_epoch=fitness_epoch+quantum_loss_train[i]
            fitness=fitness_epoch/chromosome[i,j]
#########################################################
      
       print("fitness = ",i," ",fitness[i])
       fitness_total=fitness_total+fitness[i]
    fitness_average=fitness_total/N
    i=1;
    while i<=N:
        sum_sqr=sum_sqr+pow(fitness[i]-fitness_average,2)
        i=i+1
    variance=sum_sqr/N
    if variance<=1.0e-4:
        variance=0.0
    # Best chromosome selection
    the_best_chrom=0;
    fitness_max=fitness[1];
    for i in range(1,popSize):
        if fitness[i]>=fitness_max:
            fitness_max=fitness[i]
            the_best_chrom=i
    best_chrom[generation]=the_best_chrom
    # Statistical output
    f = open("output.dat","a")
    f.write(str(generation)+" "+str(fitness_average)+"\n")
    f.write(" \n")
    f.close()
    print("Population size = ",popSize - 1)
    print("mean fitness = ",fitness_average)
    print("variance = ",variance," Std. deviation = ",math.sqrt(variance))
    print("fitness max = ",best_chrom[generation])
    print("fitness sum = ",fitness_total)

#########################################################
# QUANTUM ROTATION GATE                                 #
#########################################################
def rotation():
    rot=np.empty([2,2])
    # Lookup table of the rotation angle
    for i in range(1,popSize):
       for j in range(1,genomeLength):
           if fitness[i]<fitness[int(best_chrom[generation])]:
             # if chromosome[i,j]==0 and chromosome[best_chrom[generation],j]==0:
               if chromosome[i,j]==0 and chromosome[int(best_chrom[generation]),j]==1:
                   # Define the rotation angle: delta_theta (e.g. 0.0785398163)
                   delta_theta=0.0785398163
                   rot[0,0]=math.cos(delta_theta); rot[0,1]=-math.sin(delta_theta);
                   rot[1,0]=math.sin(delta_theta); rot[1,1]=math.cos(delta_theta);
                   nqpv[i,j,0]=(rot[0,0]*qpv[i,j,0])+(rot[0,1]*qpv[i,j,1])
                   nqpv[i,j,1]=(rot[1,0]*qpv[i,j,0])+(rot[1,1]*qpv[i,j,1])
                   qpv[i,j,0]=round(nqpv[i,j,0],2)
                   qpv[i,j,1]=round(1-nqpv[i,j,0],2)
               if chromosome[i,j]==1 and chromosome[int(best_chrom[generation]),j]==0:
                   # Define the rotation angle: delta_theta (e.g. -0.0785398163)
                   delta_theta=-0.0785398163
                   rot[0,0]=math.cos(delta_theta); rot[0,1]=-math.sin(delta_theta);
                   rot[1,0]=math.sin(delta_theta); rot[1,1]=math.cos(delta_theta);
                   nqpv[i,j,0]=(rot[0,0]*qpv[i,j,0])+(rot[0,1]*qpv[i,j,1])
                   nqpv[i,j,1]=(rot[1,0]*qpv[i,j,0])+(rot[1,1]*qpv[i,j,1])
                   qpv[i,j,0]=round(nqpv[i,j,0],2)
                   qpv[i,j,1]=round(1-nqpv[i,j,0],2)
             # if chromosome[i,j]==1 and chromosome[best_chrom[generation],j]==1:

#########################################################
# X-PAULI QUANTUM MUTATION GATE                         #
#########################################################
# pop_mutation_rate: mutation rate in the population
# mutation_rate: probability of a mutation of a bit
def mutation(pop_mutation_rate, mutation_rate):
    
    for i in range(1,popSize):
        up=np.random.random_integers(100)
        up=up/100
        if up<=pop_mutation_rate:
            for j in range(1,genomeLength):
                um=np.random.random_integers(100)
                um=um/100
                if um<=mutation_rate:
                    nqpv[i,j,0]=qpv[i,j,1]
                    nqpv[i,j,1]=qpv[i,j,0]
                else:
                    nqpv[i,j,0]=qpv[i,j,0]
                    nqpv[i,j,1]=qpv[i,j,1]
        else:
            for j in range(1,genomeLength):
                nqpv[i,j,0]=qpv[i,j,0]
                nqpv[i,j,1]=qpv[i,j,1]
    for i in range(1,popSize):
        for j in range(1,genomeLength):
            qpv[i,j,0]=nqpv[i,j,0]
            qpv[i,j,1]=nqpv[i,j,1]

#########################################################
# PERFORMANCE GRAPH                                     #
#########################################################
# Read the Docs in http://matplotlib.org/1.4.1/index.html
def plot_Output():
    data = np.loadtxt('output.dat')
    # plot the first column as x, and second column as y
    x=data[:,0]
    y=data[:,1]
    plt.plot(x,y)
    plt.xlabel('Generation')
    plt.ylabel('Fitness average')
    plt.xlim(0.0, 550.0)
    plt.show()

########################################################
#                                                      #
# MAIN PROGRAM                                         #
#                                                      #
########################################################
def Q_GA():
    generation=0
    num_qubits=3
    learning_rate =np.linspace(0.01, 0.1, int((popSize-1)/2), endpoint=True, retstep=False, dtype=None, axis=0)
    num_hidden_units = 16
    num_epoch=np.linspace(1, 10, int((popSize-1)/2), endpoint=True, retstep=False, dtype=None, axis=0)
    print("============== GENERATION: ",generation," =========================== ")
    print()
    Init_population()
    Show_population()
    Measure(0.5)
    Fitness_evaluation(generation,learning_rate,num_qubits,num_epoch)
    while (generation<generation_max-1):
      print("The best of generation [",generation,"] ", best_chrom[generation])
      print()
      print("============== GENERATION: ",generation+1," =========================== ")
      print()
      rotation()
      mutation(0.01,0.001)
      generation=generation+1
      Measure(0.5)
      Fitness_evaluation(generation,learning_rate,num_qubits,num_epoch)

print ("""QUANTUM GENETIC ALGORITHM""")
input("Press Enter to continue...")
Q_GA()
plot_Output()












QUANTUM GENETIC ALGORITHM
Press Enter to continue...
============== GENERATION:  0  =========================== 



qpv =  0  : 

0.0 0.23 0.62 0.46 
1.0 0.77 0.38 0.54 

qpv =  1  : 

0.65 0.01 0.98 0.37 
0.35 0.99 0.02 0.63 

qpv =  2  : 

0.0 0.37 0.24 0.62 
1.0 0.63 0.76 0.38 

qpv =  3  : 

0.84 0.61 0.29 1.0 
0.16 0.39 0.71 0.0 

qpv =  4  : 

0.04 0.87 0.99 0.0 
0.96 0.13 0.01 1.0 

qpv =  5  : 

0.59 0.01 0.95 0.84 
0.41 0.99 0.05 0.16 

qpv =  6  : 

0.79 0.13 0.99 0.06 
0.21 0.87 0.01 0.94 

qpv =  7  : 

0.13 0.27 0.42 0.0 
0.87 0.73 0.58 1.0 

qpv =  8  : 

0.98 0.75 0.02 0.61 
0.02 0.25 0.98 0.39 

qpv =  9  : 

0.16 0.87 0.14 0.04 
0.84 0.13 0.86 0.96 

1  1  0  1  

0  1  0  1  

1  1  1  0  

0  0  1  0  

1  0  0  1  

0  1  0  0  

0  1  0  1  

1  1  1  1  

0  0  1  0  

1  0  1  1  

weight_shapes = (n_qlayers, n_vrotations, n_qubits) = (1, 3, 3)
Untrained test
--------
Test loss: 2.820114721486598
Execution time 12.66158676147461
Epoch 0
---------
Train loss: 0.70

C:\Users\Aakash Mallik\AppData\Local\Temp\ipykernel_19460\3632062574.py:165: RuntimeWarning: invalid value encountered in scalar divide
  fitness=fitness_epoch/chromosome[i,j]


Test loss: 2.222384956147936
Execution time 13.75862741470337
Epoch 0
---------
Train loss: 0.6868493422665397
Test loss: 0.9700554797000447
Execution time 49.38681697845459


IndexError: invalid index to scalar variable.

In [ ]:
quantum_loss_train

In [20]:
import helper
import pandas as pd
# from utils import *

import time
import numpy as np
import math
import matplotlib.pyplot as plt

import torch
from torch.utils.data import DataLoader
from torch import nn

from IPython.display import Image

In [21]:
df = pd.read_csv('soil.csv')
# df = df.drop(['Date' ,'Unnamed: 0'], axis=1)
df

Ambtemp   Soiltemp      Cond        Ph  Rel_hum
0      17.52  15.124752  4.140967  7.771798       77
1      19.24  14.885414  4.645049  7.703223      100
2      15.08  10.290407  4.909317  7.774929       90
3      11.41   9.271520  5.329287  7.693409      100
4      16.18  13.978094  4.975537  7.778469      100
..       ...        ...       ...       ...      ...
239    20.17  12.388971  4.865135  7.175551      100
240    24.53  14.342893  4.863991  7.136830       98
241    29.57  16.030531  5.053619  7.124507      100
242    20.76  13.209996  4.841991  7.151910       95
243    18.51  11.409476  4.665719  7.105021      100

[244 rows x 5 columns]

In [23]:
target = "Ph"

In [24]:
features = list(df.columns.difference(["Ph"]))
features

['Ambtemp', 'Cond', 'Rel_hum', 'Soiltemp']

In [25]:
size = int(len(df) * 0.67)

df_train = df.loc[:size].copy()
df_test = df.loc[size:].copy()

In [26]:
target_mean = df_train[target].mean()
target_stdev = df_train[target].std()

for c in df_train.columns:
    mean = df_train[c].mean()
    stdev = df_train[c].std()

    df_train[c] = (df_train[c] - mean) / stdev
    df_test[c] = (df_test[c] - mean) / stdev

In [27]:
# !pip install pennylane
from Factory import SequenceDataset

In [28]:
torch.manual_seed(101)

batch_size = 1
sequence_length = 3

train_dataset = SequenceDataset(
    df_train,
    target=target,
    features=features,
    sequence_length=sequence_length
)
test_dataset = SequenceDataset(
    df_test,
    target=target,
    features=features,
    sequence_length=sequence_length
)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

X, y = next(iter(train_loader))

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: torch.Size([1, 3, 4])
Target shape: torch.Size([1])


In [29]:
def train_model(data_loader, model, loss_function, optimizer):
    num_batches = len(data_loader)
    total_loss = 0
    model.train()
    
    for X, y in data_loader:
        output = model(X)
        loss = loss_function(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / num_batches
    print(f"Train loss: {avg_loss}")
    return avg_loss

def test_model(data_loader, model, loss_function):
    
    num_batches = len(data_loader)
    total_loss = 0

    model.eval()
    with torch.no_grad():
        for X, y in data_loader:
            output = model(X)
            total_loss += loss_function(output, y).item()

    avg_loss = total_loss / num_batches
    print(f"Test loss: {avg_loss}")
    return avg_loss

In [30]:
def predict(data_loader, model):
    """Just like `test_loop` function but keep track of the outputs instead of the loss
    function.
    """
    output = torch.tensor([])
    model.eval()
    with torch.no_grad():
        for X, _ in data_loader:
            y_star = model(X)
            output = torch.cat((output, y_star), 0)
    
    return output

In [31]:
from Factory import QShallowRegressionLSTM

In [32]:


Qmodel = QShallowRegressionLSTM(num_sensors=4, hidden_units=num_hidden_units, n_qubits=4)
loss_function = nn.MSELoss()
optimizer = torch.optim.Adagrad(Qmodel.parameters(), lr=learning_rate)

weight_shapes = (n_qlayers, n_vrotations, n_qubits) = (1, 3, 4)


In [33]:
quantum_loss_train = []
quantum_loss_test = []
print("Untrained test\n--------")
start = time.time()
test_loss = test_model(test_loader, Qmodel, loss_function)
end = time.time()
print("Execution time", end - start)
quantum_loss_test.append(test_loss)

for ix_epoch in range(num_epoch):
    print(f"Epoch {ix_epoch}\n---------")
    start = time.time()
    train_loss = train_model(train_loader, Qmodel, loss_function, optimizer=optimizer)
    test_loss = test_model(test_loader, Qmodel, loss_function)
    end = time.time()
    print("Execution time", end - start)
    quantum_loss_train.append(train_loss)
    quantum_loss_test.append(test_loss)

Untrained test
--------
Test loss: 2.0590770259315585
Execution time 17.818053245544434
Epoch 0
---------
Train loss: 0.8612287103321096
Test loss: 1.0017778739149188
Execution time 68.56870627403259
Epoch 1
---------
Train loss: 0.5572293504831525
Test loss: 0.6907427507699869
Execution time 64.9932701587677
Epoch 2
---------
Train loss: 0.4965533040374949
Test loss: 0.6340047346836208
Execution time 64.3799798488617
Epoch 3
---------
Train loss: 0.46608824086713246
Test loss: 0.6835100703804606
Execution time 64.83616518974304
Epoch 4
---------
Train loss: 0.45519970958764866
Test loss: 0.6845556897126328
Execution time 67.78149056434631


In [34]:
train_eval_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)

ystar_col_Q = "Model forecast"
df_train[ystar_col_Q] = predict(train_eval_loader, Qmodel).numpy()
df_test[ystar_col_Q] = predict(test_loader, Qmodel).numpy()

df_out_Q = pd.concat((df_train, df_test))[[target, ystar_col_Q]]

for c in df_out_Q.columns:
    df_out_Q[c] = df_out_Q[c] * target_stdev + target_mean

print(df_out_Q)

           Ph  Model forecast
0    7.771798        7.673180
1    7.703223        7.530390
2    7.774929        7.610455
3    7.693409        7.689359
4    7.778469        7.780707
..        ...             ...
239  7.175551        7.195029
240  7.136830        7.230569
241  7.124507        7.279316
242  7.151910        7.232210
243  7.105021        7.201787

[245 rows x 2 columns]


In [52]:
print(chromosome)

[[3801158 6357084 6357102 7274595 6553710]
 [3342433       0       1       1       1]
 [2949221       1       0       1       1]
 [7602268       1       0       1       1]
 [6029432       1       0       1       1]
 [6029420       1       0       0       0]
 [6488169       1       0       0       1]
 [6357107       1       1       0       1]
 [7471205       1       0       1       0]
 [7471205       1       1       1       0]
 [6619250       1       1       1       0]]
